### ISSUE TITLE
Keys are missing compared to jsdom-global

### ISSUE THREAD

**Issue by iongion** [modosc/global-jsdom#118] opened 2021-03-24 11:35 UTC
After failures to test blueprintjs that expects `DocumentFragment` to exist at global level, I've investigated:

Dumping the content for key detection

```
[
        "StyleSheet",
        "MediaList",
        "CSSStyleSheet",
        "CSSRule",
        "CSSStyleRule",
        "CSSMediaRule",
        "CSSImportRule",
        "CSSStyleDeclaration",
        "XPathException",
        "XPathExpression",
        "XPathResult",
        "XPathEvaluator",
        "onafterprint",
        "onbeforeprint",
        "onbeforeunload",
        "onhashchange",
        "onlanguagechange",
        "onmessage",
        "onmessageerror",
        "onoffline",
        "ononline",
        "onpagehide",
        "onpageshow",
        "onpopstate",
        "onrejectionhandled",
        "onstorage",
        "onunhandledrejection",
        "onunload",
        "onblur",
        "onerror",
        "onfocus",
        "onload",
        "onresize",
        "onscroll",
        "onabort",
        "onautocomplete",
        "onautocompleteerror",
        "oncancel",
        "oncanplay",
        "oncanplaythrough",
        "onchange",
        "onclick",
        "onclose",
        "oncontextmenu",
        "oncuechange",
        "ondblclick",
        "ondrag",
        "ondragend",
        "ondragenter",
        "ondragexit",
        "ondragleave",
        "ondragover",
        "ondragstart",
        "ondrop",
        "ondurationchange",
        "onemptied",
        "onended",
        "oninput",
        "oninvalid",
        "onkeydown",
        "onkeypress",
        "onkeyup",
        "onloadeddata",
        "onloadedmetadata",
        "onloadstart",
        "onmousedown",
        "onmouseenter",
        "onmouseleave",
        "onmousemove",
        "onmouseout",
        "onmouseover",
        "onmouseup",
        "onwheel",
        "onpause",
        "onplay",
        "onplaying",
        "onprogress",
        "onratechange",
        "onreset",
        "onsecuritypolicyviolation",
        "onseeked",
        "onseeking",
        "onselect",
        "onsort",
        "onstalled",
        "onsubmit",
        "onsuspend",
        "ontimeupdate",
        "ontoggle",
        "onvolumechange",
        "onwaiting",
        "getSelection",
        "length",
        "window",
        "frameElement",
        "frames",
        "self",
        "parent",
        "top",
        "document",
        "external",
        "location",
        "history",
        "navigator",
        "locationbar",
        "menubar",
        "personalbar",
        "scrollbars",
        "statusbar",
        "toolbar",
        "performance",
        "screen",
        "origin",
        "localStorage",
        "sessionStorage",
        "customElements",
        "requestAnimationFrame",
        "cancelAnimationFrame",
        "postMessage",
        "atob",
        "btoa",
        "stop",
        "close",
        "getComputedStyle",
        "captureEvents",
        "releaseEvents",
        "name",
        "status",
        "devicePixelRatio",
        "innerWidth",
        "innerHeight",
        "outerWidth",
        "outerHeight",
        "pageXOffset",
        "pageYOffset",
        "screenX",
        "screenLeft",
        "screenY",
        "screenTop",
        "scrollX",
        "scrollY",
        "alert",
        "blur",
        "confirm",
        "focus",
        "moveBy",
        "moveTo",
        "open",
        "print",
        "prompt",
        "resizeBy",
        "resizeTo",
        "scroll",
        "scrollBy",
        "scrollTo",
        "addEventListener",
        "removeEventListener",
        "dispatchEvent"
      ]
```

The original `jsdom-global` project has much more keys, see here https://raw.githubusercontent.com/rstacruz/jsdom-global/master/keys.js

Can keys be exposed as options too ?

**Comment by modosc** [comment] 2021-03-24 17:38
locally it works for me:
```
laptop ~/git/global-jsdom [master|⚑ 4]$ node
Welcome to Node.js v14.10.0.
Type ".help" for more information.
> DocumentFragment
Uncaught ReferenceError: DocumentFragment is not defined
> require("./commonjs/register")
{}
> DocumentFragment
[class DocumentFragment extends Node]
```
can you post a snippet showing your issue?

**Comment by modosc** [comment] 2021-03-24 17:46
also which `jsdom` are you using?
```
> require('jsdom/package.json').version
'16.5.1'
```

**Comment by iongion** [comment] 2021-03-25 12:19
Same `jsdom`, actually is because I use the other form of injection

```
globalJsdom(html, {
  // if url isn't set then localStorage breaks with a cryptic error, see
  // https://github.com/jsdom/jsdom/issues/2304#issuecomment-408320484
  url: 'http://localhost:3000',
  // pretendToBeVisual is enabled so that react works, see
  // https://github.com/jsdom/jsdom#pretending-to-be-a-visual-browser
  pretendToBeVisual: true,
});
```

**Comment by modosc** [comment] 2021-03-25 18:14
sorry, still not seeing it on my end:
```
laptop ~/git/global-jsdom [master|⚑ 4]$ node
Welcome to Node.js v14.10.0.
Type ".help" for more information.
> const globalJsdom = require('global-jsdom')
undefined
> const html = ''
undefined
> const options = {
...   // if url isn't set then localStorage breaks with a cryptic error, see
...   // https://github.com/jsdom/jsdom/issues/2304#issuecomment-408320484
...   url: 'http://localhost:3000',
...   // pretendToBeVisual is enabled so that react works, see
...   // https://github.com/jsdom/jsdom#pretending-to-be-a-visual-browser
...   pretendToBeVisual: true,
... }
undefined
> globalJsdom(html, options)
[Function: cleanup]
> DocumentFragment
[class DocumentFragment extends Node]
```

**Comment by modosc** [comment] 2021-04-02 23:05
closing - please chime back in if you can reproduce this, thanks!

**Closed by modosc** 2021-04-02 23:05 UTC
